// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.4
// source: fulfillment/v1/fulfillment.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FulfillmentService_CreateFulfillment_FullMethodName       = "/fulfillment.v1.FulfillmentService/CreateFulfillment"
	FulfillmentService_GetFulfillment_FullMethodName          = "/fulfillment.v1.FulfillmentService/GetFulfillment"
	FulfillmentService_UpdateFulfillmentStatus_FullMethodName = "/fulfillment.v1.FulfillmentService/UpdateFulfillmentStatus"
)

// FulfillmentServiceClient is the client API for FulfillmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FulfillmentService handles warehouse dispatching, carrier handoffs, and local pickups.
type FulfillmentServiceClient interface {
	CreateFulfillment(ctx context.Context, in *CreateFulfillmentRequest, opts ...grpc.CallOption) (*CreateFulfillmentResponse, error)
	GetFulfillment(ctx context.Context, in *GetFulfillmentRequest, opts ...grpc.CallOption) (*GetFulfillmentResponse, error)
	UpdateFulfillmentStatus(ctx context.Context, in *UpdateFulfillmentStatusRequest, opts ...grpc.CallOption) (*UpdateFulfillmentStatusResponse, error)
}

type fulfillmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFulfillmentServiceClient(cc grpc.ClientConnInterface) FulfillmentServiceClient {
	return &fulfillmentServiceClient{cc}
}

func (c *fulfillmentServiceClient) CreateFulfillment(ctx context.Context, in *CreateFulfillmentRequest, opts ...grpc.CallOption) (*CreateFulfillmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFulfillmentResponse)
	err := c.cc.Invoke(ctx, FulfillmentService_CreateFulfillment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentServiceClient) GetFulfillment(ctx context.Context, in *GetFulfillmentRequest, opts ...grpc.CallOption) (*GetFulfillmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFulfillmentResponse)
	err := c.cc.Invoke(ctx, FulfillmentService_GetFulfillment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentServiceClient) UpdateFulfillmentStatus(ctx context.Context, in *UpdateFulfillmentStatusRequest, opts ...grpc.CallOption) (*UpdateFulfillmentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFulfillmentStatusResponse)
	err := c.cc.Invoke(ctx, FulfillmentService_UpdateFulfillmentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FulfillmentServiceServer is the server API for FulfillmentService service.
// All implementations must embed UnimplementedFulfillmentServiceServer
// for forward compatibility.
//
// FulfillmentService handles warehouse dispatching, carrier handoffs, and local pickups.
type FulfillmentServiceServer interface {
	CreateFulfillment(context.Context, *CreateFulfillmentRequest) (*CreateFulfillmentResponse, error)
	GetFulfillment(context.Context, *GetFulfillmentRequest) (*GetFulfillmentResponse, error)
	UpdateFulfillmentStatus(context.Context, *UpdateFulfillmentStatusRequest) (*UpdateFulfillmentStatusResponse, error)
	mustEmbedUnimplementedFulfillmentServiceServer()
}

// UnimplementedFulfillmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFulfillmentServiceServer struct{}

func (UnimplementedFulfillmentServiceServer) CreateFulfillment(context.Context, *CreateFulfillmentRequest) (*CreateFulfillmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFulfillment not implemented")
}
func (UnimplementedFulfillmentServiceServer) GetFulfillment(context.Context, *GetFulfillmentRequest) (*GetFulfillmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFulfillment not implemented")
}
func (UnimplementedFulfillmentServiceServer) UpdateFulfillmentStatus(context.Context, *UpdateFulfillmentStatusRequest) (*UpdateFulfillmentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFulfillmentStatus not implemented")
}
func (UnimplementedFulfillmentServiceServer) mustEmbedUnimplementedFulfillmentServiceServer() {}
func (UnimplementedFulfillmentServiceServer) testEmbeddedByValue()                            {}

// UnsafeFulfillmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FulfillmentServiceServer will
// result in compilation errors.
type UnsafeFulfillmentServiceServer interface {
	mustEmbedUnimplementedFulfillmentServiceServer()
}

func RegisterFulfillmentServiceServer(s grpc.ServiceRegistrar, srv FulfillmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedFulfillmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FulfillmentService_ServiceDesc, srv)
}

func _FulfillmentService_CreateFulfillment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFulfillmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentServiceServer).CreateFulfillment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulfillmentService_CreateFulfillment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentServiceServer).CreateFulfillment(ctx, req.(*CreateFulfillmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentService_GetFulfillment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFulfillmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentServiceServer).GetFulfillment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulfillmentService_GetFulfillment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentServiceServer).GetFulfillment(ctx, req.(*GetFulfillmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentService_UpdateFulfillmentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFulfillmentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentServiceServer).UpdateFulfillmentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulfillmentService_UpdateFulfillmentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentServiceServer).UpdateFulfillmentStatus(ctx, req.(*UpdateFulfillmentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FulfillmentService_ServiceDesc is the grpc.ServiceDesc for FulfillmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FulfillmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fulfillment.v1.FulfillmentService",
	HandlerType: (*FulfillmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFulfillment",
			Handler:    _FulfillmentService_CreateFulfillment_Handler,
		},
		{
			MethodName: "GetFulfillment",
			Handler:    _FulfillmentService_GetFulfillment_Handler,
		},
		{
			MethodName: "UpdateFulfillmentStatus",
			Handler:    _FulfillmentService_UpdateFulfillmentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fulfillment/v1/fulfillment.proto",
}
